/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ConvexDeployment": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ConvexUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HostedZoneId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "ProjectPlannerAiId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UpstashRedisRestToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UpstashRedisRestUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
